### ISSUE TITLE
이메일 문의

### ISSUE THREAD

**Issue by jisungbin** [sat0317/sat0317#1]
안녕하세요, 리드미에 기재된 이메일이 @google.com 이길래 문의 드립니다.
```
[cyangsa10@google.com](mailto:cyangsa10@google.com)
```
@google.com 은 구글 직원만 가능한 걸로 알고 있는데, gmail 이 아닌 google 이 맞나요?

**Comment by oriing** [comment]
세상에ㅔㅔ 정신이 나갓나봐요 종종 졸리면 저래요 수정했습니다 :)

**Comment by oriing** [comment]
어떻게 몇년동안 나를 포함해서 저걸 한 명도 발견하지 못한거지
